#!/usr/bin/env bash
#
# live-smoke.sh — run BPE's remote workflows against a real OpenBao.
#
# This is the one part of BPE's test suite that contacts a server. It stands
# up a THROWAWAY OpenBao dev server on loopback, runs the `livesmoke`-tagged
# tests against it, and tears it down again. It is never run by CI and never
# by an ordinary `go test ./...` — see internal/tui/live_smoke_test.go for
# why it exists and RUNBOOK.md Step 14 for how to read its output.
#
# Usage:
#
#   bash scripts/live-smoke.sh
#
# It takes no arguments and needs no configuration. It deliberately does not
# offer a way to point it at an existing server: the whole safety argument
# below rests on the server being one this script created and can prove is
# disposable.
#
# WHY THE GUARDS ARE NOT OPTIONAL
#
# A developer shell very often already has BAO_ADDR and BAO_TOKEN exported,
# pointing at something real. A test that wrote policies there would be
# editing production. So this script clears every inherited BAO_* and VAULT_*
# variable, sets its own, and refuses to continue unless the instance it is
# about to write to reports in-memory storage on 127.0.0.1 and holds nothing
# but the dev server's own policies. An in-memory dev server persists nothing
# and vanishes when the process exits.
#
# The root token is generated by OpenBao itself, read from a 0600 file, never
# passed as a command-line argument, never echoed, and shredded on exit.

set -euo pipefail

PORT="${BPE_SMOKE_PORT:-8211}"
ADDR="http://127.0.0.1:${PORT}"

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$repo_root"

# Nothing inherited reaches the server, the CLI, or the tests.
unset BAO_ADDR BAO_TOKEN BAO_NAMESPACE BAO_CACERT BAO_CAPATH \
      BAO_CLIENT_CERT BAO_CLIENT_KEY BAO_TLS_SERVER_NAME \
      VAULT_ADDR VAULT_TOKEN VAULT_NAMESPACE VAULT_CACERT VAULT_CAPATH \
      VAULT_CLIENT_CERT VAULT_CLIENT_KEY VAULT_TLS_SERVER_NAME 2>/dev/null || true

bao_bin=$(command -v bao || true)
[[ -z "$bao_bin" && -x "$HOME/.local/bin/bao" ]] && bao_bin="$HOME/.local/bin/bao"
[[ -z "$bao_bin" && -x /opt/homebrew/bin/bao ]] && bao_bin=/opt/homebrew/bin/bao
if [[ -z "$bao_bin" ]]; then
  echo "FATAL: no 'bao' binary found on PATH, in ~/.local/bin, or in /opt/homebrew/bin" >&2
  exit 1
fi

work_dir=$(mktemp -d -t bpe-live-smoke-XXXXXX)
chmod 700 "$work_dir"
log="${work_dir}/bao-dev.log"

server_pid=""
cleanup() {
  local rc=$?
  # Kill only the process this script started, by the pid it was given.
  if [[ -n "$server_pid" ]] && kill -0 "$server_pid" 2>/dev/null; then
    kill "$server_pid" 2>/dev/null || true
    wait "$server_pid" 2>/dev/null || true
    echo "== disposable OpenBao stopped (pid ${server_pid}) =="
  fi
  if [[ -f "$log" ]]; then
    shred -u "$log" 2>/dev/null || rm -f "$log"
  fi
  rm -rf "$work_dir"
  exit "$rc"
}
trap cleanup EXIT INT TERM

if ss -tln 2>/dev/null | grep -q ":${PORT} "; then
  echo "FATAL: something is already listening on ${PORT}." >&2
  echo "       Set BPE_SMOKE_PORT to a free loopback port and try again." >&2
  exit 1
fi

# --- the disposable server ---------------------------------------------

umask 077
: > "$log"
"$bao_bin" server -dev -dev-listen-address="127.0.0.1:${PORT}" >"$log" 2>&1 &
server_pid=$!
echo "== disposable OpenBao starting on ${ADDR} (pid ${server_pid}) =="

ready=""
for _ in $(seq 1 60); do
  if ! kill -0 "$server_pid" 2>/dev/null; then
    echo "FATAL: the dev server exited during startup." >&2
    exit 1
  fi
  if curl -fsS -o /dev/null "${ADDR}/v1/sys/health?standbyok=true&sealedcode=200&uninitcode=200" 2>/dev/null; then
    ready=yes
    break
  fi
  sleep 0.25
done
if [[ -z "$ready" ]]; then
  echo "FATAL: the dev server did not become healthy within 15 seconds." >&2
  exit 1
fi

export BAO_ADDR="$ADDR"
# The token is read from the 0600 log into a variable. It is never echoed and
# never becomes a command-line argument, where the process list would carry it.
BAO_TOKEN=$(grep -m1 'Root Token:' "$log" | awk '{print $NF}')
export BAO_TOKEN
if [[ -z "${BAO_TOKEN}" ]]; then
  echo "FATAL: no root token in the dev server's output." >&2
  exit 1
fi

# --- the guards --------------------------------------------------------

if [[ "$BAO_ADDR" != "http://127.0.0.1:"* ]]; then
  echo "FATAL: ${BAO_ADDR} is not a loopback address." >&2
  exit 1
fi

storage=$("$bao_bin" status -format=json | sed -n 's/.*"storage_type"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n1)
if [[ "$storage" != "inmem" ]]; then
  echo "FATAL: this instance reports storage_type='${storage}', not 'inmem'." >&2
  echo "       Refusing to write policies to anything that persists them." >&2
  exit 1
fi

policy_count=$("$bao_bin" policy list | wc -l | tr -d ' ')
if [[ "$policy_count" -gt 3 ]]; then
  echo "FATAL: ${policy_count} policies already exist here." >&2
  echo "       A fresh dev server has only 'default' and 'root'; this is not one." >&2
  exit 1
fi
echo "== guards passed: loopback, in-memory, ${policy_count} pre-existing policies =="

# --- the run -----------------------------------------------------------

set +e
BPE_LIVE_ADDR="$BAO_ADDR" BPE_LIVE_TOKEN="$BAO_TOKEN" \
  go test -tags livesmoke -count=1 -v ./internal/tui/ -run 'TestLive'
rc=$?
set -e

# --- prove the disposable policies are gone ----------------------------

remaining=$("$bao_bin" policy list | grep -v '^default$' | grep -v '^root$' || true)
if [[ -n "$remaining" ]]; then
  echo "WARNING: disposable policies were left behind on the throwaway server:" >&2
  echo "$remaining" >&2
  echo "         They die with the server, but a leftover means a test's cleanup did not run." >&2
  rc=1
else
  echo "== every disposable policy was removed; only default and root remain =="
fi

if [[ "$rc" -eq 0 ]]; then
  echo "== LIVE SMOKE TEST PASSED =="
else
  echo "== LIVE SMOKE TEST FAILED (exit ${rc}) ==" >&2
fi
exit "$rc"
